To decide which NGC docker to use based on the AMP demo

In [1]:
import tensorflow as tf

## Wider Dynamic Range of Single Precision

`tf.keras.backend.ones` instantiates an all-ones variable and returns it.

Below we use `tf.keras.backend.ones` to instantiate matrices of dimensions (64, 64) with all entries having the value 16.

Update the `dtype` below such that half precision is used for `half_var`.

In [2]:
# half_var = 16*tf.keras.backend.ones((64,64), dtype=None)
half_var = 16*tf.keras.backend.ones((64,64), dtype='float16')

Update the `dtype` below such that single precision is used for `single_var`

In [3]:
# single_var = 16*tf.keras.backend.ones((64,64), dtype=None)
single_var = 16*tf.keras.backend.ones((64,64), dtype='float32')

The entries can be summed up with `tf.keras.backend.sum` and we observe the results produced for the different precisions.

In [4]:
tf.keras.backend.sum(
    half_var, axis=None, keepdims=False)

<tf.Tensor: shape=(), dtype=float16, numpy=inf>

In [5]:
tf.keras.backend.sum(
    single_var, axis=None, keepdims=False)

<tf.Tensor: shape=(), dtype=float32, numpy=65536.0>

## Increased Precision of Single Precision

In [6]:
param = 1
update = 0.0001

In [7]:
half_param = tf.keras.backend.variable(value=param, dtype='float16')
half_update = tf.keras.backend.variable(value=update, dtype='float16')

In [8]:
half_param + half_update

<tf.Tensor: shape=(), dtype=float16, numpy=1.0>

In [9]:
single_param = tf.keras.backend.variable(value=param, dtype='float32')
single_update = tf.keras.backend.variable(value=update, dtype='float32')

In [10]:
single_param + single_update

<tf.Tensor: shape=(), dtype=float32, numpy=1.0001>